<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\GradeEncodingPeriod;
use App\Models\AcademicYear;
use App\Models\Semester;
use Carbon\Carbon;

class GradeEncodingPeriodSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get academic years and semesters
        $currentYear = AcademicYear::where('is_current', true)->first();
        $previousYear = AcademicYear::where('name', '2023-2024')->first();
        
        $currentSemester = Semester::where('is_current', true)->first();
        $previousSemesters = Semester::where('academic_year_id', $previousYear->id)->get();
        $firstSemesterCurrent = Semester::where('academic_year_id', $currentYear->id)
            ->where('order', 1)->first();
        
        $periods = [
            // Previous Year - First Semester (Completed)
            [
                'name' => 'Midterm Grades - First Semester 2023-2024',
                'type' => 'midterm',
                'academic_year_id' => $previousYear->id,
                'semester_id' => $previousSemesters->where('order', 1)->first()->id,
                'start_date' => '2023-10-01 00:00:00',
                'end_date' => '2023-10-15 23:59:59',
                'deadline' => '2023-10-15 23:59:59',
                'status' => 'completed',
                'priority' => 'high',
                'description' => 'Midterm grade encoding period for first semester 2023-2024',
                'instructions' => 'Please submit all midterm grades by the deadline. Late submissions will require approval.',
                'max_extensions' => 2,
                'default_extension_days' => 3,
                'send_notifications' => true,
                'reminder_days' => json_encode([7, 3, 1]),
                'auto_close' => true,
                'allow_late_submission' => true,
                'late_penalty' => 5.0,
                'grace_period_hours' => 24,
                'admin_notes' => 'Completed successfully with 95% on-time submission rate.',
                'created_at' => now()->subMonths(4),
                'updated_at' => now()->subMonths(3),
            ],
            [
                'name' => 'Final Grades - First Semester 2023-2024',
                'type' => 'final',
                'academic_year_id' => $previousYear->id,
                'semester_id' => $previousSemesters->where('order', 1)->first()->id,
                'start_date' => '2023-12-10 00:00:00',
                'end_date' => '2023-12-20 23:59:59',
                'deadline' => '2023-12-20 23:59:59',
                'status' => 'completed',
                'priority' => 'high',
                'description' => 'Final grade encoding period for first semester 2023-2024',
                'instructions' => 'Submit final grades including comprehensive exam results. Ensure all incomplete grades are properly documented.',
                'max_extensions' => 1,
                'default_extension_days' => 2,
                'send_notifications' => true,
                'reminder_days' => json_encode([10, 5, 2, 1]),
                'auto_close' => true,
                'allow_late_submission' => true,
                'late_penalty' => 10.0,
                'grace_period_hours' => 12,
                'admin_notes' => 'Extended deadline by 2 days due to system maintenance.',
                'created_at' => now()->subMonths(3),
                'updated_at' => now()->subMonths(2),
            ],
            // Previous Year - Second Semester (Completed)
            [
                'name' => 'Midterm Grades - Second Semester 2023-2024',
                'type' => 'midterm',
                'academic_year_id' => $previousYear->id,
                'semester_id' => $previousSemesters->where('order', 2)->first()->id,
                'start_date' => '2024-03-01 00:00:00',
                'end_date' => '2024-03-15 23:59:59',
                'deadline' => '2024-03-15 23:59:59',
                'status' => 'completed',
                'priority' => 'high',
                'description' => 'Midterm grade encoding period for second semester 2023-2024',
                'instructions' => 'Submit midterm grades for all enrolled students. Contact registrar for any grade change requests.',
                'max_extensions' => 2,
                'default_extension_days' => 3,
                'send_notifications' => true,
                'reminder_days' => json_encode([7, 3, 1]),
                'auto_close' => true,
                'allow_late_submission' => true,
                'late_penalty' => 5.0,
                'grace_period_hours' => 24,
                'admin_notes' => 'Smooth process with minimal issues reported.',
                'created_at' => now()->subMonths(2),
                'updated_at' => now()->subMonth(),
            ],
            [
                'name' => 'Final Grades - Second Semester 2023-2024',
                'type' => 'final',
                'academic_year_id' => $previousYear->id,
                'semester_id' => $previousSemesters->where('order', 2)->first()->id,
                'start_date' => '2024-05-20 00:00:00',
                'end_date' => '2024-05-30 23:59:59',
                'deadline' => '2024-05-30 23:59:59',
                'status' => 'completed',
                'priority' => 'high',
                'description' => 'Final grade encoding period for second semester 2023-2024',
                'instructions' => 'Final grades must be submitted before graduation ceremony. Include capstone project grades.',
                'max_extensions' => 1,
                'default_extension_days' => 2,
                'send_notifications' => true,
                'reminder_days' => json_encode([14, 7, 3, 1]),
                'auto_close' => true,
                'allow_late_submission' => false,
                'late_penalty' => 0.0,
                'grace_period_hours' => 0,
                'admin_notes' => 'Critical deadline for graduation - no extensions granted.',
                'created_at' => now()->subMonth(),
                'updated_at' => now()->subWeeks(3),
            ],
            // Current Year - First Semester (Completed)
            [
                'name' => 'Midterm Grades - First Semester 2024-2025',
                'type' => 'midterm',
                'academic_year_id' => $currentYear->id,
                'semester_id' => $firstSemesterCurrent->id,
                'start_date' => '2024-10-01 00:00:00',
                'end_date' => '2024-10-15 23:59:59',
                'deadline' => '2024-10-15 23:59:59',
                'status' => 'completed',
                'priority' => 'high',
                'description' => 'Midterm grade encoding period for first semester 2024-2025',
                'instructions' => 'Submit midterm grades for progress monitoring. Include attendance records.',
                'max_extensions' => 2,
                'default_extension_days' => 3,
                'send_notifications' => true,
                'reminder_days' => json_encode([7, 3, 1]),
                'auto_close' => true,
                'allow_late_submission' => true,
                'late_penalty' => 5.0,
                'grace_period_hours' => 24,
                'admin_notes' => 'New online system implemented successfully.',
                'created_at' => now()->subWeeks(12),
                'updated_at' => now()->subWeeks(10),
            ],
            [
                'name' => 'Final Grades - First Semester 2024-2025',
                'type' => 'final',
                'academic_year_id' => $currentYear->id,
                'semester_id' => $firstSemesterCurrent->id,
                'start_date' => '2024-12-10 00:00:00',
                'end_date' => '2024-12-20 23:59:59',
                'deadline' => '2024-12-20 23:59:59',
                'status' => 'completed',
                'priority' => 'high',
                'description' => 'Final grade encoding period for first semester 2024-2025',
                'instructions' => 'Submit all final grades including comprehensive assessments. Verify student completion status.',
                'max_extensions' => 1,
                'default_extension_days' => 2,
                'send_notifications' => true,
                'reminder_days' => json_encode([10, 5, 2, 1]),
                'auto_close' => true,
                'allow_late_submission' => true,
                'late_penalty' => 10.0,
                'grace_period_hours' => 12,
                'admin_notes' => 'Holiday break considerations - early deadline set.',
                'created_at' => now()->subWeeks(6),
                'updated_at' => now()->subWeeks(4),
            ],
            // Current Year - Second Semester (Active)
            [
                'name' => 'Midterm Grades - Second Semester 2024-2025',
                'type' => 'midterm',
                'academic_year_id' => $currentYear->id,
                'semester_id' => $currentSemester->id,
                'start_date' => '2025-03-01 00:00:00',
                'end_date' => '2025-03-15 23:59:59',
                'deadline' => '2025-03-15 23:59:59',
                'status' => 'active',
                'priority' => 'high',
                'description' => 'Midterm grade encoding period for second semester 2024-2025',
                'instructions' => 'Current midterm grading period. Submit grades for all active students. Report any issues immediately.',
                'max_extensions' => 2,
                'default_extension_days' => 3,
                'send_notifications' => true,
                'reminder_days' => json_encode([7, 3, 1]),
                'auto_close' => true,
                'allow_late_submission' => true,
                'late_penalty' => 5.0,
                'grace_period_hours' => 24,
                'admin_notes' => 'Current active period - monitor submission rates.',
                'created_at' => now()->subWeeks(2),
                'updated_at' => now()->subDays(3),
            ],
            [
                'name' => 'Final Grades - Second Semester 2024-2025',
                'type' => 'final',
                'academic_year_id' => $currentYear->id,
                'semester_id' => $currentSemester->id,
                'start_date' => '2025-05-20 00:00:00',
                'end_date' => '2025-05-30 23:59:59',
                'deadline' => '2025-05-30 23:59:59',
                'status' => 'upcoming',
                'priority' => 'high',
                'description' => 'Final grade encoding period for second semester 2024-2025',
                'instructions' => 'Upcoming final grading period. Prepare comprehensive assessments and final projects.',
                'max_extensions' => 1,
                'default_extension_days' => 2,
                'send_notifications' => true,
                'reminder_days' => json_encode([14, 7, 3, 1]),
                'auto_close' => true,
                'allow_late_submission' => false,
                'late_penalty' => 0.0,
                'grace_period_hours' => 0,
                'admin_notes' => 'Graduation deadline - strict enforcement required.',
                'created_at' => now()->subDays(7),
                'updated_at' => now()->subDays(2),
            ],
            // Special Periods
            [
                'name' => 'Summer Session Grades 2024',
                'type' => 'special',
                'academic_year_id' => $currentYear->id,
                'semester_id' => null, // Summer session not tied to regular semester
                'start_date' => '2024-07-25 00:00:00',
                'end_date' => '2024-08-05 23:59:59',
                'deadline' => '2024-08-05 23:59:59',
                'status' => 'completed',
                'priority' => 'medium',
                'description' => 'Grade encoding period for summer session courses',
                'instructions' => 'Submit grades for all summer session courses including intensive programs.',
                'max_extensions' => 1,
                'default_extension_days' => 2,
                'send_notifications' => true,
                'reminder_days' => json_encode([5, 2, 1]),
                'auto_close' => true,
                'allow_late_submission' => true,
                'late_penalty' => 3.0,
                'grace_period_hours' => 12,
                'admin_notes' => 'Summer session - accelerated timeline.',
                'created_at' => now()->subMonths(5),
                'updated_at' => now()->subMonths(4),
            ],
            [
                'name' => 'Makeup Examination Grades - Fall 2024',
                'type' => 'makeup',
                'academic_year_id' => $currentYear->id,
                'semester_id' => $firstSemesterCurrent->id,
                'start_date' => '2025-01-15 00:00:00',
                'end_date' => '2025-01-25 23:59:59',
                'deadline' => '2025-01-25 23:59:59',
                'status' => 'completed',
                'priority' => 'medium',
                'description' => 'Grade encoding for makeup examinations from fall semester',
                'instructions' => 'Submit grades for students who took makeup examinations. Include documentation.',
                'max_extensions' => 1,
                'default_extension_days' => 1,
                'send_notifications' => true,
                'reminder_days' => json_encode([3, 1]),
                'auto_close' => true,
                'allow_late_submission' => false,
                'late_penalty' => 0.0,
                'grace_period_hours' => 6,
                'admin_notes' => 'Limited to students with approved makeup exam requests.',
                'created_at' => now()->subWeeks(8),
                'updated_at' => now()->subWeeks(7),
            ],
        ];
        
        foreach ($periods as $period) {
            GradeEncodingPeriod::create($period);
        }
        
        $this->command->info('Grade Encoding Periods seeded successfully.');
    }
}